"""
Forensic PDF report generator. Returns PDF bytes. Does not write to disk.
All sections are included regardless of data availability — missing data shows as 'N/A'.
"""

import uuid
from datetime import datetime, timezone
from fpdf import FPDF
from utils.logger import get_logger

logger = get_logger(__name__)


class ForensicPDF(FPDF):
    def __init__(self, timestamp: str):
        super().__init__()
        self.timestamp = timestamp

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        # Page footer branding
        self.cell(
            0, 
            10, 
            f"Generated by Secure QR Guardian | Not a substitute for legal advice | {self.timestamp}", 
            align="C"
        )


def generate_report(all_results: dict) -> bytes:
    """
    Generates a structured PDF bytearray summarizing all forensic, OSINT, and LLM reasoning data.
    """
    try:
        now_iso = datetime.now(timezone.utc).isoformat()
        case_id = str(uuid.uuid4())
        
        # Safely extract incoming dictionaries
        payload = all_results.get("payload", {})
        osint = all_results.get("osint_bundle", {})
        risk = all_results.get("risk_result", {})
        llm = all_results.get("llm_verdict", {})
        critique = all_results.get("critique_result", {})
        final_conf = all_results.get("final_confidence", "N/A")
        archetype = all_results.get("archetype_detail", {})
        analysis = all_results.get("payload_analysis", {})
        nist_tags = all_results.get("nist_tags", [])
        
        # Initialize FPDF
        pdf = ForensicPDF(timestamp=now_iso)
        pdf.add_page()
        
        # 1. Header
        pdf.set_font("helvetica", "B", 16)
        # Using new_x="LMARGIN", new_y="NEXT" instead of deprecated ln=1 for fpdf2
        pdf.cell(0, 10, "SECURE QR GUARDIAN -- FORENSIC REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
        
        pdf.set_font("helvetica", "", 10)
        pdf.cell(0, 8, f"Case ID: {case_id}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.cell(0, 8, f"Date: {now_iso}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(10)
        
        # Utility functions for layout
        def add_section_header(title: str):
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, title, border="B", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)
            
        def add_row(key: str, value: any):
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(50, 8, f"{key}:", new_x="RIGHT")
            pdf.set_font("helvetica", "", 10)
            val_str = str(value) if value is not None and str(value).strip() != "" else "N/A"
            pdf.multi_cell(0, 8, val_str, new_x="LMARGIN", new_y="NEXT")

        # 2. Section 1 — Case Summary
        add_section_header("1. Case Summary")
        add_row("Data Type", payload.get("data_type"))
        add_row("Threat Level", risk.get("threat_level"))
        add_row("Final Score", risk.get("risk_score"))
        add_row("Confidence Interval", risk.get("confidence_interval"))
        pdf.ln(5)
        
        # 3. Section 2 — QR Payload Analysis
        add_section_header("2. QR Payload Analysis")
        add_row("SHA-256 Hash", analysis.get("sha256_hash"))
        add_row("Byte Length", analysis.get("byte_length"))
        add_row("Suspicious Patterns", analysis.get("contains_suspicious_patterns"))
        pdf.ln(5)
        
        # 4. Section 3 — OSINT Findings
        add_section_header("3. OSINT Findings")
        dom = osint.get("domain_forensics", {})
        add_row("Domain Created", dom.get("creation_date"))
        add_row("Registrar", dom.get("registrar"))
        add_row("Country", dom.get("country"))
        
        ip = osint.get("ip_analysis", {})
        add_row("IP Country", ip.get("country"))
        add_row("ASN", ip.get("asn"))
        add_row("Bulletproof", ip.get("is_known_bulletproof"))
        
        typo = osint.get("typosquat", {})
        add_row("Is Typosquat", typo.get("is_typosquat"))
        
        vpa = osint.get("vpa", {})
        add_row("VPA Mismatch", vpa.get("mismatch"))
        pdf.ln(5)
        
        # 5. Section 4 — Risk Assessment
        add_section_header("4. Risk Assessment")
        add_row("Risk Score", risk.get("risk_score"))
        add_row("Score Source", risk.get("score_source"))
        add_row("Confidence Interval", risk.get("confidence_interval"))
        pdf.ln(5)
        
        # 6. Section 5 — AI Verdict
        add_section_header("5. AI Verdict")
        add_row("Reasoning Summary", llm.get("reasoning_summary"))
        add_row("Matched Archetype", llm.get("matched_archetype"))
        add_row("Archetype Name", archetype.get("name"))
        add_row("Description", archetype.get("description"))
        pdf.ln(5)
        
        # 7. Section 6 — Self-Critique
        add_section_header("6. Self-Critique")
        add_row("Critique Summary", critique.get("critique_summary"))
        add_row("Revised Confidence", critique.get("revised_confidence"))
        pdf.ln(5)
        
        # 8. Section 7 — Hex Dump
        add_section_header("7. Hex Dump (First 32 bytes)")
        hex_dump = analysis.get("hex_dump", "")
        # Truncate to exactly first two lines (32 bytes)
        hex_lines = hex_dump.splitlines()[:2] if hex_dump else ["N/A"]
        truncated_hex = "\n".join(hex_lines)
        
        pdf.set_font("courier", "", 9)
        pdf.multi_cell(0, 5, truncated_hex, border=1, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
        # 9. Section 8 — NIST Tags
        add_section_header("8. NIST Tags")
        pdf.set_font("helvetica", "", 10)
        tags_str = ", ".join(nist_tags) if nist_tags else "N/A"
        pdf.multi_cell(0, 8, tags_str, new_x="LMARGIN", new_y="NEXT")
        
        # Output directly to bytes (dest='S' works, but new fpdf2 returns bytearray by default)
        try:
            return bytes(pdf.output(dest='S'))
        except TypeError:
            # fpdf2 fallback if dest is deprecated entirely
            return bytes(pdf.output())
            
    except Exception as e:
        logger.error(f"Error generating forensic report PDF: {e}")
        return b""
